image: gradle:alpine



variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_SSL_CAPATH: /etc/ssl/certs/
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_SUBMODULE_STRATEGY: recursive
  
before_script:
    - sh ssl_acquire.bash
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule sync --recursive
    - git submodule update --init --recursive
    
test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"